" Name:         WWDC16
" Description:  Colorful dark color scheme for Vim inspired by Apple's WWDC16 page
" Author:       Lifepillar <lifepillar@lifepillar.me>
" Maintainer:   Lifepillar <lifepillar@lifepillar.me>
" URL:          https://github.com/lifepillar/vim-wwdc16-theme
" License:      MIT
" Last Updated: 2023/7/5 19:45:18

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'wwdc16'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Conditional Statement
hi! link CurSearch Search
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Define PreProc
hi! link Exception Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Tag Special
hi! link Typedef Type
hi! link debugBreakpoint SignColumn
hi! link debugPC SignColumn
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#292c36', '#e64547', '#42a647', '#c98351', '#4670d8', '#d24e9b', '#64878f', '#949494', '#353547', '#f84547', '#95c76f', '#efa16b', '#5283ff', '#8485ce', '#00aba5', '#ffffff']
endif
hi Normal guifg=#ffffff guibg=#292c36 gui=NONE cterm=NONE
hi CursorLineNr guifg=#e64547 guibg=#353547 gui=NONE cterm=NONE
hi FoldColumn guifg=#949494 guibg=#353547 gui=NONE cterm=NONE
hi LineNr guifg=#949494 guibg=#353547 gui=NONE cterm=NONE
hi Terminal guifg=#ffffff guibg=#292c36 gui=NONE cterm=NONE
hi ColorColumn guifg=NONE guibg=#353547 gui=NONE cterm=NONE
hi Conceal guifg=#64878f guibg=NONE gui=NONE cterm=NONE
hi Cursor guifg=#ffffff guibg=#4670d8 gui=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#353547 gui=NONE cterm=NONE
hi CursorLine guifg=NONE guibg=#353547 gui=NONE cterm=NONE
hi DiffAdd guifg=#95c76f guibg=#292c36 gui=reverse cterm=reverse
hi DiffChange guifg=#c98351 guibg=#ffffff gui=reverse cterm=reverse
hi DiffDelete guifg=#e64547 guibg=#ffffff gui=reverse cterm=reverse
hi DiffText guifg=#42a647 guibg=#ffffff gui=bold,reverse cterm=bold,reverse
hi Directory guifg=#95c76f guibg=NONE gui=NONE cterm=NONE
hi EndOfBuffer guifg=#353547 guibg=NONE gui=NONE cterm=NONE
hi ErrorMsg guifg=#e64547 guibg=#ffffff gui=reverse cterm=reverse
hi Folded guifg=#949494 guibg=#353547 gui=italic cterm=italic
hi IncSearch guifg=#d24e9b guibg=#ffffff gui=standout cterm=standout
hi MatchParen guifg=#353547 guibg=#c98351 gui=bold,reverse cterm=bold,reverse
hi ModeMsg guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
hi MoreMsg guifg=#949494 guibg=NONE gui=NONE cterm=NONE
hi NonText guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
hi Pmenu guifg=#292c36 guibg=#64878f gui=NONE cterm=NONE
hi PmenuSbar guifg=#353547 guibg=#353547 gui=NONE cterm=NONE
hi PmenuSel guifg=#ffffff guibg=#c98351 gui=NONE cterm=NONE
hi PmenuThumb guifg=#353547 guibg=#c98351 gui=NONE cterm=NONE
hi Question guifg=#949494 guibg=NONE gui=NONE cterm=NONE
hi Search guifg=#c98351 guibg=#ffffff gui=reverse cterm=reverse
hi SignColumn guifg=#949494 guibg=NONE gui=NONE cterm=NONE
hi SpecialKey guifg=#949494 guibg=NONE gui=NONE cterm=NONE
hi SpellBad guifg=#8485ce guibg=NONE guisp=#d24e9b gui=undercurl cterm=undercurl
hi SpellCap guifg=#8485ce guibg=NONE guisp=#d24e9b gui=undercurl cterm=undercurl
hi SpellLocal guifg=#8485ce guibg=NONE guisp=#d24e9b gui=undercurl cterm=undercurl
hi SpellRare guifg=#8485ce guibg=NONE guisp=#d24e9b gui=undercurl cterm=undercurl
hi StatusLine guifg=#64878f guibg=#ffffff gui=reverse cterm=reverse
hi StatusLineNC guifg=#64878f guibg=#292c36 gui=reverse cterm=reverse
hi TabLine guifg=#292c36 guibg=#64878f gui=NONE cterm=NONE
hi TabLineFill guifg=#ffffff guibg=#64878f gui=NONE cterm=NONE
hi TabLineSel guifg=#ffffff guibg=#64878f gui=NONE cterm=NONE
hi Title guifg=#c98351 guibg=NONE gui=bold cterm=bold
hi VertSplit guifg=#353547 guibg=#64878f gui=NONE cterm=NONE
hi Visual guifg=#4670d8 guibg=#ffffff gui=reverse cterm=reverse
hi VisualNOS guifg=#ffffff guibg=#4670d8 gui=NONE cterm=NONE
hi WarningMsg guifg=#ffffff guibg=#db0005 gui=NONE cterm=NONE
hi WildMenu guifg=#ffffff guibg=#d24e9b gui=NONE cterm=NONE
hi Boolean guifg=#95c76f guibg=NONE gui=NONE cterm=NONE
hi Character guifg=#c98351 guibg=NONE gui=NONE cterm=NONE
hi Comment guifg=#949494 guibg=NONE gui=NONE cterm=NONE
hi Constant guifg=#c98351 guibg=NONE gui=NONE cterm=NONE
hi Debug guifg=#d24e9b guibg=NONE gui=NONE cterm=NONE
hi Delimiter guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#e64547 guibg=#ffffff gui=reverse cterm=reverse
hi Float guifg=#95c76f guibg=NONE gui=NONE cterm=NONE
hi Function guifg=#42a647 guibg=NONE gui=NONE cterm=NONE
hi Identifier guifg=#00aba5 guibg=NONE gui=NONE cterm=NONE
hi Ignore guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
hi Include guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
hi Keyword guifg=#64878f guibg=NONE gui=NONE cterm=NONE
hi Label guifg=#42a647 guibg=NONE gui=NONE cterm=NONE
hi Number guifg=#95c76f guibg=NONE gui=NONE cterm=NONE
hi Operator guifg=#00aba5 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#d24e9b guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#d24e9b guibg=NONE gui=NONE cterm=NONE
hi SpecialChar guifg=#d24e9b guibg=NONE gui=NONE cterm=NONE
hi SpecialComment guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#64878f guibg=NONE gui=NONE cterm=NONE
hi StorageClass guifg=#00aba5 guibg=NONE gui=NONE cterm=NONE
hi String guifg=#95c76f guibg=NONE gui=NONE cterm=NONE
hi Structure guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#d24e9b guibg=NONE gui=bold cterm=bold
hi Type guifg=#8485ce guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi CursorIM guifg=NONE guibg=#ffffff gui=NONE cterm=NONE
hi ToolbarLine guifg=NONE guibg=#353547 gui=NONE cterm=NONE
hi NormalMode guifg=#949494 guibg=#ffffff gui=reverse cterm=reverse
hi InsertMode guifg=#95c76f guibg=#292c36 gui=reverse cterm=reverse
hi ReplaceMode guifg=#c98351 guibg=#292c36 gui=reverse cterm=reverse
hi VisualMode guifg=#4670d8 guibg=#ffffff gui=reverse cterm=reverse
hi CommandMode guifg=#d24e9b guibg=#ffffff gui=reverse cterm=reverse
if !s:italics
  hi Folded gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  hi Normal ctermfg=231 ctermbg=236 cterm=NONE
  hi CursorLineNr ctermfg=167 ctermbg=237 cterm=NONE
  hi FoldColumn ctermfg=246 ctermbg=237 cterm=NONE
  hi LineNr ctermfg=246 ctermbg=237 cterm=NONE
  hi Terminal ctermfg=231 ctermbg=236 cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi Conceal ctermfg=66 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=231 ctermbg=26 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffAdd ctermfg=150 ctermbg=236 cterm=reverse
  hi DiffChange ctermfg=173 ctermbg=231 cterm=reverse
  hi DiffDelete ctermfg=167 ctermbg=231 cterm=reverse
  hi DiffText ctermfg=71 ctermbg=231 cterm=bold,reverse
  hi Directory ctermfg=150 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=237 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=231 cterm=reverse
  hi Folded ctermfg=246 ctermbg=237 cterm=italic
  hi IncSearch ctermfg=169 ctermbg=231 cterm=standout
  hi MatchParen ctermfg=237 ctermbg=173 cterm=bold,reverse
  hi ModeMsg ctermfg=231 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=246 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=231 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=236 ctermbg=66 cterm=NONE
  hi PmenuSbar ctermfg=237 ctermbg=237 cterm=NONE
  hi PmenuSel ctermfg=231 ctermbg=173 cterm=NONE
  hi PmenuThumb ctermfg=237 ctermbg=173 cterm=NONE
  hi Question ctermfg=246 ctermbg=NONE cterm=NONE
  hi Search ctermfg=173 ctermbg=231 cterm=reverse
  hi SignColumn ctermfg=246 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=246 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=104 ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=104 ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=104 ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=104 ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=66 ctermbg=231 cterm=reverse
  hi StatusLineNC ctermfg=66 ctermbg=236 cterm=reverse
  hi TabLine ctermfg=236 ctermbg=66 cterm=NONE
  hi TabLineFill ctermfg=231 ctermbg=66 cterm=NONE
  hi TabLineSel ctermfg=231 ctermbg=66 cterm=NONE
  hi Title ctermfg=173 ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=237 ctermbg=66 cterm=NONE
  hi Visual ctermfg=26 ctermbg=231 cterm=reverse
  hi VisualNOS ctermfg=231 ctermbg=26 cterm=NONE
  hi WarningMsg ctermfg=231 ctermbg=167 cterm=NONE
  hi WildMenu ctermfg=231 ctermbg=169 cterm=NONE
  hi Boolean ctermfg=150 ctermbg=NONE cterm=NONE
  hi Character ctermfg=173 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=246 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=173 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=169 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=231 ctermbg=NONE cterm=NONE
  hi Error ctermfg=167 ctermbg=231 cterm=reverse
  hi Float ctermfg=150 ctermbg=NONE cterm=NONE
  hi Function ctermfg=71 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=37 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=231 ctermbg=NONE cterm=NONE
  hi Include ctermfg=167 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=66 ctermbg=NONE cterm=NONE
  hi Label ctermfg=71 ctermbg=NONE cterm=NONE
  hi Number ctermfg=150 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=37 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=169 ctermbg=NONE cterm=NONE
  hi Special ctermfg=169 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=169 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=167 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=66 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=37 ctermbg=NONE cterm=NONE
  hi String ctermfg=150 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=167 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=169 ctermbg=NONE cterm=bold
  hi Type ctermfg=104 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=231 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi NormalMode ctermfg=246 ctermbg=231 cterm=reverse
  hi InsertMode ctermfg=150 ctermbg=236 cterm=reverse
  hi ReplaceMode ctermfg=173 ctermbg=236 cterm=reverse
  hi VisualMode ctermfg=26 ctermbg=231 cterm=reverse
  hi CommandMode ctermfg=169 ctermbg=231 cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background:  dark
" Color: black                #292c36              236        Black
" Color: red                  #e64547              167        DarkRed
" Color: green                #42a647               71        DarkGreen
" Color: yellow               #c98351              173        DarkYellow
" Color: blue                 #4670d8               26        DarkBlue
" Color: magenta              #d24e9b              169        DarkMagenta
" Color: cyan                 #64878f               66        DarkCyan
" Color: white                #949494              246        Gray
" Color: brightblack          #353547              237        DarkGray
" Color: brightred            #f84547              203        Red
" Color: brightgreen          #95c76f              150        Green
" Color: brightyellow         #efa16b              216        Yellow
" Color: brightblue           #5283ff               69        Blue
" Color: brightmagenta        #8485ce              104        Magenta
" Color: brightcyan           #00aba5               37        Cyan
" Color: brightwhite          #ffffff              231        White
" Color: myred                #db0005              167        DarkRed
" Term Colors: black       red       green       yellow       blue       magenta       cyan       white
" Term Colors: brightblack brightred brightgreen brightyellow brightblue brightmagenta brightcyan brightwhite
" vim: et ts=8 sw=2 sts=2
